//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcSborka.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periphery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periphery()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MonitorID { get; set; }
        public Nullable<int> MouseID { get; set; }
        public Nullable<int> KeyboardID { get; set; }
    
        public virtual Keyboard Keyboard { get; set; }
        public virtual Monitor Monitor { get; set; }
        public virtual Mouse Mouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
<<<<<<< HEAD

        public double SumPeriphery { get; set; }
=======
>>>>>>> cbbf8d9f865399896303020726371375ab28ec26
    }
}
